global:
  extraPodAnnotations: {}

  extraLabels: {}

  prometheusAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"

  env:
    httpsProxy:
    noProxy: 10.0.0.0/8,172.0.0.0/8

kraan:
  crd:
    enabled: true
  rbac:
    enabled: true
  netpolicy:
    enabled: true
  kraanController:
    enabled: true
    name: kraan-controller

    extraPodAnnotations: {}

    extraLabels: {}

    prometheus:
      enabled: true

    imagePullSecrets:
      name:

    image:
      repository: kraan
      name: kraan-controller
      tag:
      imagePullPolicy:

    args:
      logLevel: 0
      syncPeriod: 1m

    devmode: false

    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 128Mi

    tolerations:
      []
      # - key: "key"
      #   operator: "Equal|Exists"
      #   value: "value"
      #   effect: "NoSchedule|PreferNoSchedule|NoExecute(1.6 only)"

    ## Node labels for alertmanager pod assignment
    ## Ref: https://kubernetes.io/docs/user-guide/node-selection/
    ##
    nodeSelector: {}

    ## Pod affinity
    ##
    affinity: {}

gotk:
  rbac:
    enabled: true
  netpolicy:
    enabled: true

  sourceController:
    crd:
      enabled: true
    enabled: true

    name: source-controller

    extraPodAnnotations: {}

    extraLabels: {}

    prometheus:
      enabled: true

    image:
      repository: ghcr.io/fluxcd
      name: source-controller
      tag: v0.7.1
      imagePullPolicy:

    imagePullSecrets:
      name:

    proxy: true

    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 128Mi

    tolerations:
      []
      # - key: "key"
      #   operator: "Equal|Exists"
      #   value: "value"
      #   effect: "NoSchedule|PreferNoSchedule|NoExecute(1.6 only)"

    ## Node labels for alertmanager pod assignment
    ## Ref: https://kubernetes.io/docs/user-guide/node-selection/
    ##
    nodeSelector: {}

    ## Pod affinity
    ##
    affinity: {}

  helmController:
    crd:
      enabled: true
    enabled: true

    name: helm-controller

    extraPodAnnotations: {}

    extraLabels: {}

    prometheus:
      enabled: true

    imagePullSecrets:
      name:

    image:
      repository: ghcr.io/fluxcd
      name: helm-controller
      tag: v0.6.1
      imagePullPolicy:

    proxy: true

    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 128Mi

    tolerations:
      []
      # - key: "key"
      #   operator: "Equal|Exists"
      #   value: "value"
      #   effect: "NoSchedule|PreferNoSchedule|NoExecute(1.6 only)"

    ## Node labels for alertmanager pod assignment
    ## Ref: https://kubernetes.io/docs/user-guide/node-selection/
    ##
    nodeSelector: {}

    ## Pod affinity
    ##
    affinity: {}
