# permissions for end users to view addons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: addons-viewer-role
rules:
- apiGroups:
  - kraan.io
  resources:
  - addonslayers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kraan.io
  resources:
  - addons/status
  verbs:
  - get
