# permissions for end users to edit addons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: addons-editor-role
rules:
- apiGroups:
  - kraan.io
  resources:
  - addonslayers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kraan.io
  resources:
  - addons/status
  verbs:
  - get
